name: AI Component CI

on:
  push:
    paths:
      - 'oware-cartesi-ai/**'
    branches:
      - develop
      - 'feature/**'
  pull_request:
    paths:
      - 'oware-cartesi-ai/**'
    branches:
      - develop

jobs:
  test-and-build-ai:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'  # Ensure this matches the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r oware-cartesi-ai/src/requirements.txt  # Assuming you have a requirements file

    - name: Lint with Flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 oware-cartesi-ai/src --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 oware-cartesi-ai/src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: |
        pip install pytest
        pytest oware-cartesi-ai/tests


